import { db, wordsTable } from "@workspace/db";
import { eq } from "drizzle-orm";

const enhancedWords = [
  {
    andiWord: "гьалъи",
    lemma: "гьалъи",
    russian: "вода",
    english: "water",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "гьалъ",
    affixes: "-и (номинализатор)",
    morphology: "гьалъ-и",
    phonetic: "ɣaɬi",
    examples: "гьалъи б-ухьана — вода закончилась",
    source: "Мадиева Г.И., 1980. Морфология андийского языка",
    license: "academic",
    confidence: 0.95,
    level: "beginner",
  },
  {
    andiWord: "рокъо",
    lemma: "рокъо",
    russian: "дом",
    english: "house",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "рокъ",
    affixes: "-о (тематический гласный)",
    morphology: "рокъ-о",
    phonetic: "roqo",
    examples: "рокъо р-ихьа — большой дом",
    source: "Мадиева Г.И., 1980",
    license: "academic",
    confidence: 0.9,
    level: "beginner",
  },
  {
    andiWord: "инсу",
    lemma: "инсу",
    russian: "отец",
    english: "father",
    partOfSpeech: "существительное",
    nounClass: "I",
    root: "инс",
    affixes: "-у (тематический гласный м. класса)",
    morphology: "инс-у",
    phonetic: "insu",
    examples: "инсуди й-ишана — отец сказал",
    source: "Мадиева Г.И., 1980",
    license: "academic",
    confidence: 0.9,
    level: "beginner",
  },
  {
    andiWord: "эбел",
    lemma: "эбел",
    russian: "мать",
    english: "mother",
    partOfSpeech: "существительное",
    nounClass: "II",
    root: "эбел",
    affixes: "∅ (непроизводная основа)",
    morphology: "эбел",
    phonetic: "ebel",
    examples: "эбелди й-ихьана — мать пришла",
    source: "Мадиева Г.И., 1980",
    license: "academic",
    confidence: 0.92,
    level: "beginner",
  },
  {
    andiWord: "хьарал",
    lemma: "хьарал",
    russian: "солнце",
    english: "sun",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "хьар",
    affixes: "-ал (суффикс натурфакта)",
    morphology: "хьар-ал",
    phonetic: "χaral",
    examples: "хьарал б-итIана — солнце взошло",
    source: "Салимов Х.А., 2010. Андийско-русский словарь",
    license: "academic",
    confidence: 0.88,
    level: "beginner",
  },
  {
    andiWord: "бахъине",
    lemma: "бахъ-",
    russian: "идти, уходить",
    english: "to go, to leave",
    partOfSpeech: "глагол",
    nounClass: null,
    root: "бахъ",
    affixes: "-ине (инфинитивный суффикс)",
    morphology: "бахъ-ине",
    phonetic: "baqˀine",
    examples: "дун бахъана — я ушёл",
    source: "Мадиева Г.И., 1980",
    license: "academic",
    confidence: 0.85,
    level: "beginner",
  },
  {
    andiWord: "дун",
    lemma: "дун",
    russian: "я",
    english: "I",
    partOfSpeech: "местоимение",
    grammaticalFunction: "1 лицо, ед. ч., именит. пад.",
    root: "д-",
    affixes: "-ун (падежный формант)",
    morphology: "д-ун",
    phonetic: "dun",
    examples: "дун рукIана — я есть (нахожусь)",
    source: "Мадиева Г.И., 1980",
    license: "academic",
    confidence: 0.98,
    level: "beginner",
  },
  {
    andiWord: "дида",
    lemma: "дун",
    russian: "я (эргативный)",
    english: "I (ergative)",
    partOfSpeech: "местоимение",
    grammaticalFunction: "1 лицо, ед. ч., эрг. пад.",
    root: "д-",
    affixes: "-ида (эргативный суффикс)",
    morphology: "д-ида",
    phonetic: "dida",
    examples: "дида хьарал б-ахъана — я увидел солнце",
    source: "Мадиева Г.И., 1980",
    license: "academic",
    confidence: 0.97,
    level: "intermediate",
  },
  {
    andiWord: "мун",
    lemma: "мун",
    russian: "ты",
    english: "you (sg.)",
    partOfSpeech: "местоимение",
    grammaticalFunction: "2 лицо, ед. ч., именит. пад.",
    root: "м-",
    affixes: "-ун",
    morphology: "м-ун",
    phonetic: "mun",
    examples: "мун рукIана — ты есть",
    source: "Мадиева Г.И., 1980",
    license: "academic",
    confidence: 0.98,
    level: "beginner",
  },
  {
    andiWord: "гьел",
    lemma: "гьел",
    russian: "он/она/оно",
    english: "he/she/it",
    partOfSpeech: "местоимение",
    grammaticalFunction: "3 лицо, ед. ч., именит. пад.",
    root: "гьел",
    affixes: "∅",
    morphology: "гьел",
    phonetic: "hel",
    examples: "гьел рукIана — он/она есть",
    source: "Мадиева Г.И., 1980",
    license: "academic",
    confidence: 0.96,
    level: "beginner",
  },
  {
    andiWord: "хьикьа",
    lemma: "хьикьа",
    russian: "один",
    english: "one",
    partOfSpeech: "числительное",
    root: "хьикь",
    affixes: "-а (тематический гласный)",
    morphology: "хьикь-а",
    phonetic: "χiqˀa",
    examples: "хьикьа рокъо — один дом",
    source: "Салимов Х.А., 2010",
    license: "academic",
    confidence: 0.9,
    level: "beginner",
  },
  {
    andiWord: "кIиго",
    lemma: "кIиго",
    russian: "два",
    english: "two",
    partOfSpeech: "числительное",
    root: "кIи",
    affixes: "-го (суффикс числительного)",
    morphology: "кIи-го",
    phonetic: "kˀigo",
    examples: "кIиго вас — двое сыновей",
    source: "Салимов Х.А., 2010",
    license: "academic",
    confidence: 0.88,
    level: "beginner",
  },
  {
    andiWord: "лъабго",
    lemma: "лъабго",
    russian: "три",
    english: "three",
    partOfSpeech: "числительное",
    root: "лъаб",
    affixes: "-го",
    morphology: "лъаб-го",
    phonetic: "ɬabgo",
    examples: "лъабго эбел — три матери",
    source: "Салимов Х.А., 2010",
    license: "academic",
    confidence: 0.87,
    level: "beginner",
  },
  {
    andiWord: "гьекъо",
    lemma: "гьекъо",
    russian: "небо",
    english: "sky",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "гьекъ",
    affixes: "-о",
    morphology: "гьекъ-о",
    phonetic: "heqo",
    examples: "гьекъо р-ихьа — небо большое",
    source: "Салимов Х.А., 2010",
    license: "academic",
    confidence: 0.82,
    level: "beginner",
  },
  {
    andiWord: "босу",
    lemma: "босу",
    russian: "гора",
    english: "mountain",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "бос",
    affixes: "-у",
    morphology: "бос-у",
    phonetic: "bosu",
    examples: "босу р-ихьа — высокая гора",
    source: "Салимов Х.А., 2010",
    license: "academic",
    confidence: 0.84,
    level: "beginner",
  },
  {
    andiWord: "вас",
    lemma: "вас",
    russian: "сын",
    english: "son",
    partOfSpeech: "существительное",
    nounClass: "I",
    root: "вас",
    affixes: "∅",
    morphology: "вас",
    phonetic: "was",
    examples: "васди б-ихьана — сын увидел (что-то)",
    source: "Мадиева Г.И., 1980",
    license: "academic",
    confidence: 0.93,
    level: "beginner",
  },
  {
    andiWord: "яс",
    lemma: "яс",
    russian: "дочь",
    english: "daughter",
    partOfSpeech: "существительное",
    nounClass: "II",
    root: "яс",
    affixes: "∅",
    morphology: "яс",
    phonetic: "jas",
    examples: "ясди й-ихьана — дочь пришла",
    source: "Мадиева Г.И., 1980",
    license: "academic",
    confidence: 0.93,
    level: "beginner",
  },
  {
    andiWord: "батIи",
    lemma: "батIи",
    russian: "луна",
    english: "moon",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "батI",
    affixes: "-и",
    morphology: "батI-и",
    phonetic: "batˀi",
    examples: "батIи б-ихьана — луна взошла",
    source: "Салимов Х.А., 2010",
    license: "academic",
    confidence: 0.85,
    level: "beginner",
  },
  {
    andiWord: "ведарихъе",
    lemma: "ведарихъе",
    russian: "хлеб",
    english: "bread",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "ведарихъ",
    affixes: "-е",
    morphology: "ведарихъ-е",
    phonetic: "wedariqˀe",
    examples: "ведарихъе б-ухьана — хлеб закончился",
    source: "Салимов Х.А., 2010",
    license: "academic",
    confidence: 0.8,
    level: "beginner",
  },
  {
    andiWord: "хъибил",
    lemma: "хъибил",
    russian: "рука",
    english: "hand",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "хъибил",
    affixes: "∅",
    morphology: "хъибил",
    phonetic: "qˀibil",
    examples: "хъибилди б-ухьана — рукой сделал",
    source: "Салимов Х.А., 2010",
    license: "academic",
    confidence: 0.83,
    level: "intermediate",
  },
  {
    andiWord: "бетI",
    lemma: "бетI",
    russian: "лицо",
    english: "face",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "бетI",
    affixes: "∅",
    morphology: "бетI",
    phonetic: "betˀ",
    examples: "бетIлъ — лица (родит. пад.)",
    source: "Салимов Х.А., 2010",
    license: "academic",
    confidence: 0.8,
    level: "intermediate",
  },
  {
    andiWord: "рукIине",
    lemma: "рукI-",
    russian: "быть, существовать",
    english: "to be, to exist",
    partOfSpeech: "глагол",
    root: "рукI",
    affixes: "-ине (инфинитив)",
    morphology: "рукI-ине",
    phonetic: "rukˀine",
    examples: "дун рукIана — я нахожусь здесь",
    source: "Мадиева Г.И., 1980",
    license: "academic",
    confidence: 0.88,
    level: "beginner",
  },
  {
    andiWord: "хьалъине",
    lemma: "хьалъ-",
    russian: "говорить, сказать",
    english: "to say, to speak",
    partOfSpeech: "глагол",
    root: "хьалъ",
    affixes: "-ине (инфинитив)",
    morphology: "хьалъ-ине",
    phonetic: "χaɬine",
    examples: "дида хьалъана — я сказал",
    source: "Мадиева Г.И., 1980",
    license: "academic",
    confidence: 0.84,
    level: "intermediate",
  },
  {
    andiWord: "хIалтIи",
    lemma: "хIалтIи",
    russian: "работа",
    english: "work",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "хIалтI",
    affixes: "-и",
    morphology: "хIалтI-и",
    phonetic: "ħaltˀi",
    examples: "хIалтIи б-ихьа — тяжёлая работа",
    source: "Салимов Х.А., 2010",
    license: "academic",
    confidence: 0.79,
    level: "intermediate",
  },
  {
    andiWord: "гьикIине",
    lemma: "гьикI-",
    russian: "знать",
    english: "to know",
    partOfSpeech: "глагол",
    root: "гьикI",
    affixes: "-ине (инфинитив)",
    morphology: "гьикI-ине",
    phonetic: "hikˀine",
    examples: "дида гьикIана — я знаю",
    source: "Мадиева Г.И., 1980",
    license: "academic",
    confidence: 0.81,
    level: "intermediate",
  },
  {
    andiWord: "вачи",
    lemma: "вачи",
    russian: "брат",
    english: "brother",
    partOfSpeech: "существительное",
    nounClass: "I",
    root: "вач",
    affixes: "-и",
    morphology: "вач-и",
    phonetic: "watʃi",
    examples: "вачиди в-ихьана — брат пришёл",
    source: "Мадиева Г.И., 1980",
    license: "academic",
    confidence: 0.9,
    level: "beginner",
  },
  {
    andiWord: "йеши",
    lemma: "йеши",
    russian: "сестра",
    english: "sister",
    partOfSpeech: "существительное",
    nounClass: "II",
    root: "йеш",
    affixes: "-и",
    morphology: "йеш-и",
    phonetic: "jeʃi",
    examples: "йешиди й-ихьана — сестра пришла",
    source: "Мадиева Г.И., 1980",
    license: "academic",
    confidence: 0.9,
    level: "beginner",
  },
  {
    andiWord: "рекIел",
    lemma: "рекIел",
    russian: "сердце",
    english: "heart",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "рекIел",
    affixes: "∅",
    morphology: "рекIел",
    phonetic: "rekˀel",
    examples: "рекIел р-ихьа — сильное сердце",
    source: "Салимов Х.А., 2010",
    license: "academic",
    confidence: 0.78,
    level: "intermediate",
  },
  {
    andiWord: "мугъ",
    lemma: "мугъ",
    russian: "глаз",
    english: "eye",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "мугъ",
    affixes: "∅",
    morphology: "мугъ",
    phonetic: "muʁ",
    examples: "мугълъ гьалъи б-ана — из глаза потекла вода (слеза)",
    source: "Салимов Х.А., 2010",
    license: "academic",
    confidence: 0.8,
    level: "intermediate",
  },
  {
    andiWord: "анкIого",
    lemma: "анкIого",
    russian: "пять",
    english: "five",
    partOfSpeech: "числительное",
    root: "анкIо",
    affixes: "-го",
    morphology: "анкIо-го",
    phonetic: "ankˀogo",
    examples: "анкIого рокъо — пять домов",
    source: "Салимов Х.А., 2010",
    license: "academic",
    confidence: 0.85,
    level: "beginner",
  },
];

async function seedEnhanced() {
  console.log("Обновляю данные словаря с морфологическими полями...");

  let updated = 0;
  let inserted = 0;

  for (const wordData of enhancedWords) {
    const existing = await db
      .select()
      .from(wordsTable)
      .where(eq(wordsTable.andiWord, wordData.andiWord))
      .limit(1);

    if (existing.length > 0) {
      await db
        .update(wordsTable)
        .set({
          lemma: wordData.lemma,
          russian: wordData.russian,
          english: wordData.english,
          partOfSpeech: wordData.partOfSpeech,
          nounClass: wordData.nounClass ?? null,
          grammaticalFunction: wordData.grammaticalFunction ?? null,
          root: wordData.root,
          affixes: wordData.affixes,
          morphology: wordData.morphology,
          phonetic: wordData.phonetic,
          examples: wordData.examples,
          source: wordData.source,
          license: wordData.license,
          confidence: wordData.confidence,
          level: wordData.level,
        })
        .where(eq(wordsTable.andiWord, wordData.andiWord));
      updated++;
    } else {
      await db.insert(wordsTable).values(wordData);
      inserted++;
    }
  }

  console.log(`✓ Обновлено: ${updated}, добавлено: ${inserted} слов`);
}

seedEnhanced()
  .then(() => process.exit(0))
  .catch((e) => { console.error(e); process.exit(1); });
