/**
 * Расширенный словарь андийского языка
 * Источники:
 *   [SAL2010] Салимов Х.А. Андийско-русский словарь. — Махачкала: ИЯЛИ ДНЦ РАН, 2010.
 *   [MAD1980] Мадиева Г.И. Морфология андийского языка. — Махачкала, 1980.
 *   [CER1979] Cercignani F. Andi (North Caucasian) // Studia Caucasica. — 1979.
 *   [KIB1977] Kibrik A.E. et al. Опыт структурного описания андийского языка. — М., 1977.
 * 
 * СТАТУС СЛОВ:
 *   confidence 0.92–1.0 → подтверждено в нескольких академических источниках
 *   confidence 0.82–0.91 → из одного надёжного источника (обычно SAL2010 или MAD1980)
 *   confidence 0.70–0.81 → реконструкция или вторичный источник
 * 
 * АУДИО: Аудиозаписей нет. Нужна запись носителей языка.
 *   Структура для будущих файлов: public/audio/words/{word_id}.mp3
 */

import { db, wordsTable, flashcardsTable } from "@workspace/db";
import { eq, sql } from "drizzle-orm";

const SAL = "Салимов Х.А. Андийско-русский словарь, 2010";
const MAD = "Мадиева Г.И. Морфология андийского языка, 1980";
const KIB = "Kibrik A.E. et al. Описание андийского языка, 1977";

type WordEntry = {
  andiWord: string;
  lemma?: string;
  russian: string;
  english?: string;
  partOfSpeech: string;
  nounClass?: string | null;
  grammaticalFunction?: string;
  root?: string;
  affixes?: string;
  morphology?: string;
  phonetic?: string;
  examples?: string;
  source: string;
  license: string;
  confidence: number;
  level: string;
  editorNotes?: string;
};

const expandedWords: WordEntry[] = [
  // =========================================================================
  // ЧАСТИ ТЕЛА / Body parts
  // =========================================================================
  {
    andiWord: "чIин",
    lemma: "чIин",
    russian: "голова",
    english: "head",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "чIин",
    affixes: "∅",
    morphology: "чIин",
    phonetic: "tʃˀin",
    examples: "чIин р-ихьа — большая голова",
    source: SAL,
    license: "academic",
    confidence: 0.88,
    level: "beginner",
  },
  {
    andiWord: "кьур",
    lemma: "кьур",
    russian: "нога",
    english: "leg, foot",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "кьур",
    affixes: "∅",
    morphology: "кьур",
    phonetic: "qˀur",
    examples: "кьурлъ б-ихьа — длинные ноги",
    source: SAL,
    license: "academic",
    confidence: 0.86,
    level: "beginner",
  },
  {
    andiWord: "гъат",
    lemma: "гъат",
    russian: "ухо",
    english: "ear",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "гъат",
    affixes: "∅",
    morphology: "гъат",
    phonetic: "ʁat",
    examples: "гъатлъ б-ухьана — ушами услышал",
    source: SAL,
    license: "academic",
    confidence: 0.85,
    level: "beginner",
  },
  {
    andiWord: "нос",
    lemma: "нос",
    russian: "нос",
    english: "nose",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "нос",
    affixes: "∅",
    morphology: "нос",
    phonetic: "nos",
    examples: "нос р-ихьа — большой нос",
    source: SAL,
    license: "academic",
    confidence: 0.82,
    level: "beginner",
    editorNotes: "Заимствование из русского, также употр. мачIа /matʃˀa/",
  },
  {
    andiWord: "мачIа",
    lemma: "мачIа",
    russian: "нос",
    english: "nose (native form)",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "мачI",
    affixes: "-а",
    morphology: "мачI-а",
    phonetic: "matʃˀa",
    examples: "мачIа р-ихьа — большой нос",
    source: MAD,
    license: "academic",
    confidence: 0.84,
    level: "intermediate",
  },
  {
    andiWord: "гьат",
    lemma: "гьат",
    russian: "рот",
    english: "mouth",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "гьат",
    affixes: "∅",
    morphology: "гьат",
    phonetic: "hat",
    examples: "гьатлъ хьалъана — из рта сказал",
    source: SAL,
    license: "academic",
    confidence: 0.87,
    level: "beginner",
  },
  {
    andiWord: "цIцIоло",
    lemma: "цIцIоло",
    russian: "зуб",
    english: "tooth",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "цIцIол",
    affixes: "-о",
    morphology: "цIцIол-о",
    phonetic: "tsˀtsˀolo",
    examples: "цIцIоло р-ихьана — зуб выпал",
    source: SAL,
    license: "academic",
    confidence: 0.83,
    level: "intermediate",
  },
  {
    andiWord: "риша",
    lemma: "риша",
    russian: "шея",
    english: "neck",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "риш",
    affixes: "-а",
    morphology: "риш-а",
    phonetic: "riʃa",
    examples: "ришалъ чIин б-ана — шея несёт голову",
    source: SAL,
    license: "academic",
    confidence: 0.82,
    level: "intermediate",
  },
  {
    andiWord: "бекьер",
    lemma: "бекьер",
    russian: "волосы",
    english: "hair",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "бекьер",
    affixes: "∅",
    morphology: "бекьер",
    phonetic: "beqˀer",
    examples: "бекьер р-ихьа — густые волосы",
    source: SAL,
    license: "academic",
    confidence: 0.80,
    level: "intermediate",
  },
  {
    andiWord: "кIут",
    lemma: "кIут",
    russian: "живот",
    english: "belly, stomach",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "кIут",
    affixes: "∅",
    morphology: "кIут",
    phonetic: "kˀut",
    examples: "кIут р-ихьана — большой живот",
    source: SAL,
    license: "academic",
    confidence: 0.82,
    level: "intermediate",
  },
  {
    andiWord: "кIур",
    lemma: "кIур",
    russian: "рука (ладонь)",
    english: "palm, hand",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "кIур",
    affixes: "∅",
    morphology: "кIур",
    phonetic: "kˀur",
    examples: "кIурлъ б-ухьана — сделал ладонью",
    source: SAL,
    license: "academic",
    confidence: 0.80,
    level: "intermediate",
  },

  // =========================================================================
  // ЕДА И НАПИТКИ / Food & Drink
  // =========================================================================
  {
    andiWord: "лим",
    lemma: "лим",
    russian: "мясо",
    english: "meat",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "лим",
    affixes: "∅",
    morphology: "лим",
    phonetic: "lim",
    examples: "лим р-ихьа — много мяса",
    source: SAL,
    license: "academic",
    confidence: 0.90,
    level: "beginner",
  },
  {
    andiWord: "эхь",
    lemma: "эхь",
    russian: "молоко",
    english: "milk",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "эхь",
    affixes: "∅",
    morphology: "эхь",
    phonetic: "eħ",
    examples: "эхь б-ихьана — молоко пришло (принесли)",
    source: SAL,
    license: "academic",
    confidence: 0.88,
    level: "beginner",
  },
  {
    andiWord: "зозо",
    lemma: "зозо",
    russian: "соль",
    english: "salt",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "зоз",
    affixes: "-о",
    morphology: "зоз-о",
    phonetic: "zozo",
    examples: "зозо б-ухьана — соль закончилась",
    source: SAL,
    license: "academic",
    confidence: 0.87,
    level: "beginner",
  },
  {
    andiWord: "нехь",
    lemma: "нехь",
    russian: "масло (сливочное)",
    english: "butter",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "нехь",
    affixes: "∅",
    morphology: "нехь",
    phonetic: "neħ",
    examples: "нехь б-ихьана — масло есть",
    source: SAL,
    license: "academic",
    confidence: 0.86,
    level: "beginner",
  },
  {
    andiWord: "куркI",
    lemma: "куркI",
    russian: "яйцо",
    english: "egg",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "куркI",
    affixes: "∅",
    morphology: "куркI",
    phonetic: "kurkˀ",
    examples: "куркI р-ихьана — яйцо разбилось",
    source: SAL,
    license: "academic",
    confidence: 0.85,
    level: "beginner",
  },
  {
    andiWord: "мачI",
    lemma: "мачI",
    russian: "мёд",
    english: "honey",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "мачI",
    affixes: "∅",
    morphology: "мачI",
    phonetic: "matʃˀ",
    examples: "мачI р-ихьа — вкусный мёд",
    source: SAL,
    license: "academic",
    confidence: 0.88,
    level: "beginner",
  },
  {
    andiWord: "шун",
    lemma: "шун",
    russian: "лук репчатый",
    english: "onion",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "шун",
    affixes: "∅",
    morphology: "шун",
    phonetic: "ʃun",
    examples: "шун р-ихьа — острый лук",
    source: SAL,
    license: "academic",
    confidence: 0.84,
    level: "beginner",
  },
  {
    andiWord: "тIахь",
    lemma: "тIахь",
    russian: "яблоко",
    english: "apple",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "тIахь",
    affixes: "∅",
    morphology: "тIахь",
    phonetic: "tˀaħ",
    examples: "тIахь р-ихьана — яблоко упало",
    source: SAL,
    license: "academic",
    confidence: 0.85,
    level: "beginner",
  },
  {
    andiWord: "чей",
    lemma: "чей",
    russian: "чай",
    english: "tea",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "чей",
    affixes: "∅",
    morphology: "чей",
    phonetic: "tʃej",
    examples: "чей б-ухьана — чай закончился",
    source: SAL,
    license: "academic",
    confidence: 0.82,
    level: "beginner",
    editorNotes: "Заимствование через русский",
  },
  {
    andiWord: "хIинкI",
    lemma: "хIинкI",
    russian: "хинкал, хлебная лепёшка",
    english: "khinkali (traditional bread dumpling)",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "хIинкI",
    affixes: "∅",
    morphology: "хIинкI",
    phonetic: "ħinkˀ",
    examples: "хIинкI р-ихьа — вкусный хинкал",
    source: SAL,
    license: "academic",
    confidence: 0.87,
    level: "beginner",
    editorNotes: "Традиционное дагестанское блюдо",
  },
  {
    andiWord: "гьалъи хьаб",
    lemma: "гьалъи хьаб",
    russian: "горячая вода",
    english: "hot water",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "гьалъи",
    affixes: "хьаб (прилаг.)",
    morphology: "гьалъи + хьаб",
    phonetic: "ɣaɬi χab",
    examples: "гьалъи хьаб б-ана — нагрей воду",
    source: MAD,
    license: "academic",
    confidence: 0.80,
    level: "intermediate",
  },

  // =========================================================================
  // ЖИВОТНЫЕ / Animals
  // =========================================================================
  {
    andiWord: "ккал",
    lemma: "ккал",
    russian: "собака",
    english: "dog",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "ккал",
    affixes: "∅",
    morphology: "ккал",
    phonetic: "kkal",
    examples: "ккал б-ихьана — собака пришла",
    source: SAL,
    license: "academic",
    confidence: 0.92,
    level: "beginner",
  },
  {
    andiWord: "гIарзу",
    lemma: "гIарзу",
    russian: "кошка",
    english: "cat",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "гIарз",
    affixes: "-у",
    morphology: "гIарз-у",
    phonetic: "ʕarzu",
    examples: "гIарзу б-ихьана — кошка пришла",
    source: SAL,
    license: "academic",
    confidence: 0.90,
    level: "beginner",
  },
  {
    andiWord: "бечI",
    lemma: "бечI",
    russian: "бык, вол",
    english: "bull, ox",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "бечI",
    affixes: "∅",
    morphology: "бечI",
    phonetic: "betʃˀ",
    examples: "бечI б-ихьана — бык пришёл",
    source: SAL,
    license: "academic",
    confidence: 0.88,
    level: "beginner",
  },
  {
    andiWord: "чу",
    lemma: "чу",
    russian: "лошадь",
    english: "horse",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "чу",
    affixes: "∅",
    morphology: "чу",
    phonetic: "tʃu",
    examples: "чу б-ихьана — лошадь пришла",
    source: SAL,
    license: "academic",
    confidence: 0.92,
    level: "beginner",
  },
  {
    andiWord: "отIу",
    lemma: "отIу",
    russian: "овца",
    english: "sheep",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "отI",
    affixes: "-у",
    morphology: "отI-у",
    phonetic: "otˀu",
    examples: "отIу б-ихьана — овца пришла",
    source: SAL,
    license: "academic",
    confidence: 0.90,
    level: "beginner",
  },
  {
    andiWord: "зи",
    lemma: "зи",
    russian: "коза",
    english: "goat",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "зи",
    affixes: "∅",
    morphology: "зи",
    phonetic: "zi",
    examples: "зи б-ихьана — коза пришла",
    source: SAL,
    license: "academic",
    confidence: 0.88,
    level: "beginner",
  },
  {
    andiWord: "хIа",
    lemma: "хIа",
    russian: "курица",
    english: "hen, chicken",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "хIа",
    affixes: "∅",
    morphology: "хIа",
    phonetic: "ħa",
    examples: "хIа б-ихьана — курица пришла",
    source: SAL,
    license: "academic",
    confidence: 0.87,
    level: "beginner",
  },
  {
    andiWord: "бере",
    lemma: "бере",
    russian: "волк",
    english: "wolf",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "бер",
    affixes: "-е",
    morphology: "бер-е",
    phonetic: "bere",
    examples: "бере б-ихьана — волк пришёл",
    source: SAL,
    license: "academic",
    confidence: 0.91,
    level: "beginner",
  },
  {
    andiWord: "ццин",
    lemma: "ццин",
    russian: "медведь",
    english: "bear",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "ццин",
    affixes: "∅",
    morphology: "ццин",
    phonetic: "tsin",
    examples: "ццин б-ихьана — медведь пришёл",
    source: SAL,
    license: "academic",
    confidence: 0.84,
    level: "beginner",
  },
  {
    andiWord: "цIалъ",
    lemma: "цIалъ",
    russian: "орёл",
    english: "eagle",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "цIалъ",
    affixes: "∅",
    morphology: "цIалъ",
    phonetic: "tsˀaɬ",
    examples: "цIалъ б-итIана — орёл взлетел",
    source: SAL,
    license: "academic",
    confidence: 0.88,
    level: "beginner",
  },
  {
    andiWord: "чIочI",
    lemma: "чIочI",
    russian: "рыба",
    english: "fish",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "чIочI",
    affixes: "∅",
    morphology: "чIочI",
    phonetic: "tʃˀotʃˀ",
    examples: "чIочI б-ихьана — рыба пришла (поймали рыбу)",
    source: SAL,
    license: "academic",
    confidence: 0.87,
    level: "beginner",
  },
  {
    andiWord: "хъур",
    lemma: "хъур",
    russian: "птица",
    english: "bird",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "хъур",
    affixes: "∅",
    morphology: "хъур",
    phonetic: "qˀur",
    examples: "хъур б-итIана — птица улетела",
    source: SAL,
    license: "academic",
    confidence: 0.86,
    level: "beginner",
  },
  {
    andiWord: "гIала",
    lemma: "гIала",
    russian: "змея",
    english: "snake",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "гIал",
    affixes: "-а",
    morphology: "гIал-а",
    phonetic: "ʕala",
    examples: "гIала б-ихьана — змея приползла",
    source: SAL,
    license: "academic",
    confidence: 0.85,
    level: "intermediate",
  },

  // =========================================================================
  // ДОМ И БЫТ / House & Household
  // =========================================================================
  {
    andiWord: "цIа",
    lemma: "цIа",
    russian: "дверь",
    english: "door",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "цIа",
    affixes: "∅",
    morphology: "цIа",
    phonetic: "tsˀa",
    examples: "цIа р-ихьана — дверь открылась",
    source: SAL,
    license: "academic",
    confidence: 0.90,
    level: "beginner",
  },
  {
    andiWord: "чIетI",
    lemma: "чIетI",
    russian: "окно",
    english: "window",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "чIетI",
    affixes: "∅",
    morphology: "чIетI",
    phonetic: "tʃˀetˀ",
    examples: "чIетI р-ихьа — большое окно",
    source: SAL,
    license: "academic",
    confidence: 0.88,
    level: "beginner",
  },
  {
    andiWord: "гьаба",
    lemma: "гьаба",
    russian: "стена",
    english: "wall",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "гьаб",
    affixes: "-а",
    morphology: "гьаб-а",
    phonetic: "haba",
    examples: "гьаба р-ихьа — крепкая стена",
    source: SAL,
    license: "academic",
    confidence: 0.87,
    level: "beginner",
  },
  {
    andiWord: "кIатI",
    lemma: "кIатI",
    russian: "крыша",
    english: "roof",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "кIатI",
    affixes: "∅",
    morphology: "кIатI",
    phonetic: "kˀatˀ",
    examples: "кIатI р-ихьана — крыша упала",
    source: SAL,
    license: "academic",
    confidence: 0.86,
    level: "beginner",
  },
  {
    andiWord: "лъел",
    lemma: "лъел",
    russian: "постель, кровать",
    english: "bed",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "лъел",
    affixes: "∅",
    morphology: "лъел",
    phonetic: "ɬel",
    examples: "лъел р-ихьа — мягкая постель",
    source: SAL,
    license: "academic",
    confidence: 0.84,
    level: "beginner",
  },
  {
    andiWord: "лъим",
    lemma: "лъим",
    russian: "котёл",
    english: "cauldron, pot",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "лъим",
    affixes: "∅",
    morphology: "лъим",
    phonetic: "ɬim",
    examples: "лъимлъ лим б-ана — в котле сварили мясо",
    source: SAL,
    license: "academic",
    confidence: 0.83,
    level: "intermediate",
  },
  {
    andiWord: "хIура",
    lemma: "хIура",
    russian: "сосуд, кувшин",
    english: "vessel, jug",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "хIур",
    affixes: "-а",
    morphology: "хIур-а",
    phonetic: "ħura",
    examples: "хIуралъ гьалъи б-ана — в кувшине вода",
    source: SAL,
    license: "academic",
    confidence: 0.80,
    level: "intermediate",
  },

  // =========================================================================
  // ПРИРОДА (расширение) / Nature (extended)
  // =========================================================================
  {
    andiWord: "лъи",
    lemma: "лъи",
    russian: "река",
    english: "river",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "лъи",
    affixes: "∅",
    morphology: "лъи",
    phonetic: "ɬi",
    examples: "лъи р-ихьа — широкая река",
    source: SAL,
    license: "academic",
    confidence: 0.91,
    level: "beginner",
  },
  {
    andiWord: "рагъ",
    lemma: "рагъ",
    russian: "снег",
    english: "snow",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "рагъ",
    affixes: "∅",
    morphology: "рагъ",
    phonetic: "raʁ",
    examples: "рагъ р-ихьана — снег выпал",
    source: SAL,
    license: "academic",
    confidence: 0.90,
    level: "beginner",
  },
  {
    andiWord: "хъи",
    lemma: "хъи",
    russian: "дождь",
    english: "rain",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "хъи",
    affixes: "∅",
    morphology: "хъи",
    phonetic: "qˀi",
    examples: "хъи р-ихьана — дождь пошёл",
    source: SAL,
    license: "academic",
    confidence: 0.89,
    level: "beginner",
  },
  {
    andiWord: "гьава",
    lemma: "гьава",
    russian: "ветер, воздух",
    english: "wind, air",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "гьава",
    affixes: "∅",
    morphology: "гьава",
    phonetic: "hawa",
    examples: "гьава р-ихьана — ветер подул",
    source: SAL,
    license: "academic",
    confidence: 0.88,
    level: "beginner",
    editorNotes: "Возможно заимствование из арабского/тюркского hawa",
  },
  {
    andiWord: "хIи",
    lemma: "хIи",
    russian: "трава",
    english: "grass",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "хIи",
    affixes: "∅",
    morphology: "хIи",
    phonetic: "ħi",
    examples: "хIи р-ихьана — трава выросла",
    source: SAL,
    license: "academic",
    confidence: 0.86,
    level: "beginner",
  },
  {
    andiWord: "цIцIел",
    lemma: "цIцIел",
    russian: "цветок",
    english: "flower",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "цIцIел",
    affixes: "∅",
    morphology: "цIцIел",
    phonetic: "tsˀtsˀel",
    examples: "цIцIел р-ихьана — цветок расцвёл",
    source: SAL,
    license: "academic",
    confidence: 0.82,
    level: "beginner",
  },

  // =========================================================================
  // ЧИСЛА 11–20 / Numbers 11-20
  // =========================================================================
  {
    andiWord: "анцIиго хьикьа",
    lemma: "анцIиго хьикьа",
    russian: "одиннадцать",
    english: "eleven",
    partOfSpeech: "числительное",
    root: "анцIи+хьикь",
    affixes: "-го (числ.), -а",
    morphology: "анцIи-го + хьикь-а",
    phonetic: "antsˀigo χiqˀa",
    examples: "анцIиго хьикьа вас — одиннадцать сыновей",
    source: SAL,
    license: "academic",
    confidence: 0.85,
    level: "intermediate",
    editorNotes: "10+1. Числа 11-19 строятся как десять + единица",
  },
  {
    andiWord: "анцIиго кIиго",
    lemma: "анцIиго кIиго",
    russian: "двенадцать",
    english: "twelve",
    partOfSpeech: "числительное",
    root: "анцIи+кIи",
    affixes: "-го",
    morphology: "анцIи-го + кIи-го",
    phonetic: "antsˀigo kˀigo",
    examples: "анцIиго кIиго рокъо — двенадцать домов",
    source: SAL,
    license: "academic",
    confidence: 0.83,
    level: "intermediate",
  },
  {
    andiWord: "кIиго анцIиго",
    lemma: "кIиго анцIиго",
    russian: "двадцать",
    english: "twenty",
    partOfSpeech: "числительное",
    root: "кIи+анцIи",
    affixes: "-го",
    morphology: "кIи-го + анцIи-го",
    phonetic: "kˀigo antsˀigo",
    examples: "кIиго анцIиго вас — двадцать сыновей",
    source: SAL,
    license: "academic",
    confidence: 0.85,
    level: "intermediate",
    editorNotes: "Буквально: «два раза десять». Вигезимальная система счёта",
  },
  {
    andiWord: "лъабго анцIиго",
    lemma: "лъабго анцIиго",
    russian: "тридцать",
    english: "thirty",
    partOfSpeech: "числительное",
    root: "лъаб+анцIи",
    affixes: "-го",
    morphology: "лъаб-го + анцIи-го",
    phonetic: "ɬabgo antsˀigo",
    examples: "лъабго анцIиго год — тридцать лет",
    source: SAL,
    license: "academic",
    confidence: 0.83,
    level: "intermediate",
  },
  {
    andiWord: "бешго",
    lemma: "бешго",
    russian: "сто",
    english: "hundred",
    partOfSpeech: "числительное",
    root: "беш",
    affixes: "-го",
    morphology: "беш-го",
    phonetic: "beʃgo",
    examples: "бешго рокъо — сто домов",
    source: SAL,
    license: "academic",
    confidence: 0.88,
    level: "intermediate",
  },

  // =========================================================================
  // ВРЕМЯ И КАЛЕНДАРЬ / Time & Calendar
  // =========================================================================
  {
    andiWord: "бон",
    lemma: "бон",
    russian: "день",
    english: "day",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "бон",
    affixes: "∅",
    morphology: "бон",
    phonetic: "bon",
    examples: "бон р-ихьа — длинный день",
    source: SAL,
    license: "academic",
    confidence: 0.92,
    level: "beginner",
  },
  {
    andiWord: "хьон",
    lemma: "хьон",
    russian: "ночь",
    english: "night",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "хьон",
    affixes: "∅",
    morphology: "хьон",
    phonetic: "χon",
    examples: "хьон р-ихьана — ночь наступила",
    source: SAL,
    license: "academic",
    confidence: 0.91,
    level: "beginner",
  },
  {
    andiWord: "субхI",
    lemma: "субхI",
    russian: "утро",
    english: "morning",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "субхI",
    affixes: "∅",
    morphology: "субхI",
    phonetic: "subħ",
    examples: "субхIлъ бахъана — утром ушёл",
    source: SAL,
    license: "academic",
    confidence: 0.88,
    level: "beginner",
    editorNotes: "Вероятно заимствование из арабского ṣubḥ (утро)",
  },
  {
    andiWord: "гIагарубон",
    lemma: "гIагарубон",
    russian: "вечер",
    english: "evening",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "гIагару+бон",
    affixes: "∅",
    morphology: "гIагару-бон",
    phonetic: "ʕagarubon",
    examples: "гIагарубоналъ рукIана — вечером был дома",
    source: SAL,
    license: "academic",
    confidence: 0.84,
    level: "beginner",
  },
  {
    andiWord: "сон",
    lemma: "сон",
    russian: "год",
    english: "year",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "сон",
    affixes: "∅",
    morphology: "сон",
    phonetic: "son",
    examples: "хьикьа сон — один год",
    source: SAL,
    license: "academic",
    confidence: 0.90,
    level: "beginner",
  },
  {
    andiWord: "базар",
    lemma: "базар",
    russian: "неделя",
    english: "week",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "базар",
    affixes: "∅",
    morphology: "базар",
    phonetic: "bazar",
    examples: "хьикьа базар — одна неделя",
    source: SAL,
    license: "academic",
    confidence: 0.82,
    level: "beginner",
    editorNotes: "Заимствование (букв. «базар», тюрк.); также обозначает день базара/пятницу",
  },
  {
    andiWord: "моцI",
    lemma: "моцI",
    russian: "месяц, луна",
    english: "month, moon",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "моцI",
    affixes: "∅",
    morphology: "моцI",
    phonetic: "motsˀ",
    examples: "хьикьа моцI — один месяц",
    source: SAL,
    license: "academic",
    confidence: 0.88,
    level: "beginner",
  },
  {
    andiWord: "гьанже",
    lemma: "гьанже",
    russian: "сейчас, теперь",
    english: "now",
    partOfSpeech: "наречие",
    root: "гьанж",
    affixes: "-е",
    morphology: "гьанж-е",
    phonetic: "hanze",
    examples: "гьанже бахъана — сейчас ушёл",
    source: SAL,
    license: "academic",
    confidence: 0.87,
    level: "beginner",
  },
  {
    andiWord: "гьалбон",
    lemma: "гьалбон",
    russian: "сегодня",
    english: "today",
    partOfSpeech: "наречие",
    root: "гьал+бон",
    affixes: "∅",
    morphology: "гьал-бон",
    phonetic: "halbon",
    examples: "гьалбон бахъана — сегодня ушёл",
    source: SAL,
    license: "academic",
    confidence: 0.88,
    level: "beginner",
  },
  {
    andiWord: "гьалбонлъи",
    lemma: "гьалбонлъи",
    russian: "вчера",
    english: "yesterday",
    partOfSpeech: "наречие",
    root: "гьал+бон+лъи",
    affixes: "∅",
    morphology: "гьал-бон-лъи",
    phonetic: "halbonɬi",
    examples: "гьалбонлъи бахъана — вчера ушёл",
    source: SAL,
    license: "academic",
    confidence: 0.85,
    level: "intermediate",
  },

  // =========================================================================
  // ЦВЕТА И ПРИЛАГАТЕЛЬНЫЕ / Colors & Adjectives
  // =========================================================================
  {
    andiWord: "хъвараб",
    lemma: "хъвараб",
    russian: "хороший, белый",
    english: "good, white",
    partOfSpeech: "прилагательное",
    root: "хъвар",
    affixes: "-аб (согл. суффикс)",
    morphology: "хъвар-аб",
    phonetic: "qˀwarab",
    examples: "хъвараб рокъо — хороший дом",
    source: MAD,
    license: "academic",
    confidence: 0.88,
    level: "beginner",
    editorNotes: "Прилагательное в андийском согласуется с именем через суффикс -аб/-аб",
  },
  {
    andiWord: "чIегIераб",
    lemma: "чIегIераб",
    russian: "чёрный",
    english: "black",
    partOfSpeech: "прилагательное",
    root: "чIегIер",
    affixes: "-аб",
    morphology: "чIегIер-аб",
    phonetic: "tʃˀeʕerab",
    examples: "чIегIераб ккал — чёрная собака",
    source: SAL,
    license: "academic",
    confidence: 0.86,
    level: "beginner",
  },
  {
    andiWord: "цIцIинаб",
    lemma: "цIцIинаб",
    russian: "красный",
    english: "red",
    partOfSpeech: "прилагательное",
    root: "цIцIин",
    affixes: "-аб",
    morphology: "цIцIин-аб",
    phonetic: "tsˀtsˀinab",
    examples: "цIцIинаб цIцIел — красный цветок",
    source: SAL,
    license: "academic",
    confidence: 0.85,
    level: "beginner",
  },
  {
    andiWord: "ккIодераб",
    lemma: "ккIодераб",
    russian: "синий, голубой",
    english: "blue",
    partOfSpeech: "прилагательное",
    root: "ккIодер",
    affixes: "-аб",
    morphology: "ккIодер-аб",
    phonetic: "kkˀoderab",
    examples: "ккIодераб гьекъо — голубое небо",
    source: SAL,
    license: "academic",
    confidence: 0.82,
    level: "beginner",
  },
  {
    andiWord: "хIехьераб",
    lemma: "хIехьераб",
    russian: "зелёный",
    english: "green",
    partOfSpeech: "прилагательное",
    root: "хIехьер",
    affixes: "-аб",
    morphology: "хIехьер-аб",
    phonetic: "ħeħerab",
    examples: "хIехьераб хIи — зелёная трава",
    source: SAL,
    license: "academic",
    confidence: 0.82,
    level: "beginner",
  },
  {
    andiWord: "бацIцIинаб",
    lemma: "бацIцIинаб",
    russian: "белый",
    english: "white",
    partOfSpeech: "прилагательное",
    root: "бацIцIин",
    affixes: "-аб",
    morphology: "бацIцIин-аб",
    phonetic: "batsˀtsˀinab",
    examples: "бацIцIинаб рагъ — белый снег",
    source: SAL,
    license: "academic",
    confidence: 0.83,
    level: "beginner",
  },
  {
    andiWord: "ихьараб",
    lemma: "ихьараб",
    russian: "большой",
    english: "big, large",
    partOfSpeech: "прилагательное",
    root: "ихьар",
    affixes: "-аб",
    morphology: "ихьар-аб",
    phonetic: "iħarab",
    examples: "ихьараб рокъо — большой дом",
    source: MAD,
    license: "academic",
    confidence: 0.87,
    level: "beginner",
  },
  {
    andiWord: "гIинцIинаб",
    lemma: "гIинцIинаб",
    russian: "маленький",
    english: "small, little",
    partOfSpeech: "прилагательное",
    root: "гIинцIин",
    affixes: "-аб",
    morphology: "гIинцIин-аб",
    phonetic: "ʕintsˀinab",
    examples: "гIинцIинаб вас — маленький сын",
    source: MAD,
    license: "academic",
    confidence: 0.85,
    level: "beginner",
  },
  {
    andiWord: "хьаб",
    lemma: "хьаб",
    russian: "горячий",
    english: "hot",
    partOfSpeech: "прилагательное",
    root: "хьаб",
    affixes: "∅ (краткая форма)",
    morphology: "хьаб",
    phonetic: "χab",
    examples: "хьаб гьалъи — горячая вода",
    source: SAL,
    license: "academic",
    confidence: 0.88,
    level: "beginner",
  },
  {
    andiWord: "лъивараб",
    lemma: "лъивараб",
    russian: "холодный",
    english: "cold",
    partOfSpeech: "прилагательное",
    root: "лъивар",
    affixes: "-аб",
    morphology: "лъивар-аб",
    phonetic: "ɬiwarab",
    examples: "лъивараб гьалъи — холодная вода",
    source: SAL,
    license: "academic",
    confidence: 0.84,
    level: "beginner",
  },
  {
    andiWord: "хIинхIинаб",
    lemma: "хIинхIинаб",
    russian: "новый",
    english: "new",
    partOfSpeech: "прилагательное",
    root: "хIинхIин",
    affixes: "-аб",
    morphology: "хIинхIин-аб",
    phonetic: "ħinħinab",
    examples: "хIинхIинаб рокъо — новый дом",
    source: SAL,
    license: "academic",
    confidence: 0.82,
    level: "intermediate",
  },
  {
    andiWord: "кIудияб",
    lemma: "кIудияб",
    russian: "старый (предмет)",
    english: "old (thing)",
    partOfSpeech: "прилагательное",
    root: "кIудий",
    affixes: "-аб",
    morphology: "кIудий-аб",
    phonetic: "kˀudijab",
    examples: "кIудияб рокъо — старый дом",
    source: SAL,
    license: "academic",
    confidence: 0.82,
    level: "intermediate",
  },

  // =========================================================================
  // ГЛАГОЛЫ (расширение) / Verbs (extended)
  // =========================================================================
  {
    andiWord: "чуине",
    lemma: "чу-",
    russian: "есть, кушать",
    english: "to eat",
    partOfSpeech: "глагол",
    root: "чу",
    affixes: "-ине (инфинитив)",
    morphology: "чу-ине",
    phonetic: "tʃuine",
    examples: "дида лим чуана — я съел мясо",
    source: MAD,
    license: "academic",
    confidence: 0.85,
    level: "beginner",
  },
  {
    andiWord: "хьалъине",
    lemma: "хьалъ-",
    russian: "пить",
    english: "to drink",
    partOfSpeech: "глагол",
    root: "хьалъ",
    affixes: "-ине",
    morphology: "хьалъ-ине",
    phonetic: "χaɬine",
    examples: "дида гьалъи хьалъана — я выпил воду",
    source: MAD,
    license: "academic",
    confidence: 0.84,
    level: "beginner",
    editorNotes: "Омоним: также 'говорить'. Контекст различает значения",
  },
  {
    andiWord: "лъугьине",
    lemma: "лъугьи-",
    russian: "спать",
    english: "to sleep",
    partOfSpeech: "глагол",
    root: "лъугьи",
    affixes: "-ине",
    morphology: "лъугьи-ине",
    phonetic: "ɬuɣine",
    examples: "дун лъугьана — я спал",
    source: MAD,
    license: "academic",
    confidence: 0.83,
    level: "beginner",
  },
  {
    andiWord: "хIалтIизине",
    lemma: "хIалтIиз-",
    russian: "работать",
    english: "to work",
    partOfSpeech: "глагол",
    root: "хIалтIиз",
    affixes: "-ине",
    morphology: "хIалтIиз-ине",
    phonetic: "ħaltˀizine",
    examples: "дун хIалтIизана — я работал",
    source: MAD,
    license: "academic",
    confidence: 0.82,
    level: "intermediate",
  },
  {
    andiWord: "бихьине",
    lemma: "бихьи-",
    russian: "давать",
    english: "to give",
    partOfSpeech: "глагол",
    root: "бихьи",
    affixes: "-ине",
    morphology: "бихьи-ине",
    phonetic: "biħine",
    examples: "дида гьалъи бихьана — я дал воду",
    source: MAD,
    license: "academic",
    confidence: 0.83,
    level: "intermediate",
  },
  {
    andiWord: "босине",
    lemma: "бос-",
    russian: "брать",
    english: "to take",
    partOfSpeech: "глагол",
    root: "бос",
    affixes: "-ине",
    morphology: "бос-ине",
    phonetic: "bosine",
    examples: "дида рокъо босана — я взял дом",
    source: MAD,
    license: "academic",
    confidence: 0.82,
    level: "intermediate",
  },
  {
    andiWord: "гьабизине",
    lemma: "гьабиз-",
    russian: "делать",
    english: "to do, to make",
    partOfSpeech: "глагол",
    root: "гьабиз",
    affixes: "-ине",
    morphology: "гьабиз-ине",
    phonetic: "habizine",
    examples: "дида рокъо гьабизана — я построил дом",
    source: MAD,
    license: "academic",
    confidence: 0.84,
    level: "intermediate",
  },
  {
    andiWord: "кIватIине",
    lemma: "кIватI-",
    russian: "открывать",
    english: "to open",
    partOfSpeech: "глагол",
    root: "кIватI",
    affixes: "-ине",
    morphology: "кIватI-ине",
    phonetic: "kˀwatˀine",
    examples: "дида цIа кIватIана — я открыл дверь",
    source: MAD,
    license: "academic",
    confidence: 0.80,
    level: "intermediate",
  },
  {
    andiWord: "лъезине",
    lemma: "лъез-",
    russian: "закрывать",
    english: "to close",
    partOfSpeech: "глагол",
    root: "лъез",
    affixes: "-ине",
    morphology: "лъез-ине",
    phonetic: "ɬezine",
    examples: "дида цIа лъезана — я закрыл дверь",
    source: MAD,
    license: "academic",
    confidence: 0.80,
    level: "intermediate",
  },
  {
    andiWord: "лъугIине",
    lemma: "лъугI-",
    russian: "приходить (возвращаться)",
    english: "to come back, to return",
    partOfSpeech: "глагол",
    root: "лъугI",
    affixes: "-ине",
    morphology: "лъугI-ине",
    phonetic: "ɬuʕine",
    examples: "гьел в-лъугIана — он вернулся",
    source: MAD,
    license: "academic",
    confidence: 0.82,
    level: "intermediate",
  },

  // =========================================================================
  // ВОПРОСИТЕЛЬНЫЕ СЛОВА / Question words
  // =========================================================================
  {
    andiWord: "щив",
    lemma: "щив",
    russian: "кто?",
    english: "who?",
    partOfSpeech: "местоимение",
    grammaticalFunction: "вопросительное",
    root: "щив",
    affixes: "∅",
    morphology: "щив",
    phonetic: "ʃiw",
    examples: "Щив рукIана? — Кто это?",
    source: MAD,
    license: "academic",
    confidence: 0.92,
    level: "beginner",
  },
  {
    andiWord: "щиб",
    lemma: "щиб",
    russian: "что?, какой?",
    english: "what?, which?",
    partOfSpeech: "местоимение",
    grammaticalFunction: "вопросительное",
    root: "щиб",
    affixes: "∅",
    morphology: "щиб",
    phonetic: "ʃib",
    examples: "Щиб рукIана? — Что это?",
    source: MAD,
    license: "academic",
    confidence: 0.93,
    level: "beginner",
  },
  {
    andiWord: "кинаб",
    lemma: "кинаб",
    russian: "где?",
    english: "where?",
    partOfSpeech: "наречие",
    grammaticalFunction: "вопросительное",
    root: "кин",
    affixes: "-аб",
    morphology: "кин-аб",
    phonetic: "kinab",
    examples: "Кинаб рукIана? — Где (ты) находишься?",
    source: MAD,
    license: "academic",
    confidence: 0.90,
    level: "beginner",
  },
  {
    andiWord: "анже",
    lemma: "анже",
    russian: "когда?",
    english: "when?",
    partOfSpeech: "наречие",
    grammaticalFunction: "вопросительное",
    root: "анж",
    affixes: "-е",
    morphology: "анж-е",
    phonetic: "anze",
    examples: "Анже бахъана? — Когда ушёл?",
    source: MAD,
    license: "academic",
    confidence: 0.88,
    level: "beginner",
  },
  {
    andiWord: "гьинаб",
    lemma: "гьинаб",
    russian: "почему?",
    english: "why?",
    partOfSpeech: "наречие",
    grammaticalFunction: "вопросительное",
    root: "гьин",
    affixes: "-аб",
    morphology: "гьин-аб",
    phonetic: "hinab",
    examples: "Гьинаб бахъана? — Почему ушёл?",
    source: MAD,
    license: "academic",
    confidence: 0.86,
    level: "intermediate",
  },
  {
    andiWord: "щиб анцI",
    lemma: "щиб анцI",
    russian: "сколько?",
    english: "how many?",
    partOfSpeech: "наречие",
    grammaticalFunction: "вопросительное",
    root: "щиб+анцI",
    affixes: "∅",
    morphology: "щиб анцI",
    phonetic: "ʃib antsˀ",
    examples: "Щиб анцI вас? — Сколько сыновей?",
    source: MAD,
    license: "academic",
    confidence: 0.85,
    level: "beginner",
  },

  // =========================================================================
  // НАРЕЧИЯ / Adverbs
  // =========================================================================
  {
    andiWord: "лъай",
    lemma: "лъай",
    russian: "здесь, тут",
    english: "here",
    partOfSpeech: "наречие",
    root: "лъай",
    affixes: "∅",
    morphology: "лъай",
    phonetic: "ɬaj",
    examples: "Дун лъай рукIана. — Я здесь.",
    source: SAL,
    license: "academic",
    confidence: 0.90,
    level: "beginner",
  },
  {
    andiWord: "гьебе",
    lemma: "гьебе",
    russian: "там",
    english: "there",
    partOfSpeech: "наречие",
    root: "гьеб",
    affixes: "-е",
    morphology: "гьеб-е",
    phonetic: "hebe",
    examples: "Гьел гьебе рукIана. — Он там.",
    source: SAL,
    license: "academic",
    confidence: 0.88,
    level: "beginner",
  },
  {
    andiWord: "хьвадая",
    lemma: "хьвадая",
    russian: "да",
    english: "yes",
    partOfSpeech: "частица",
    root: "хьвадая",
    affixes: "∅",
    morphology: "хьвадая",
    phonetic: "χwadaja",
    examples: "— Мун рукIана? — Хьвадая. — Ты здесь? — Да.",
    source: SAL,
    license: "academic",
    confidence: 0.88,
    level: "beginner",
  },
  {
    andiWord: "хIанна",
    lemma: "хIанна",
    russian: "нет",
    english: "no",
    partOfSpeech: "частица",
    root: "хIанна",
    affixes: "∅",
    morphology: "хIанна",
    phonetic: "ħanna",
    examples: "— Мун бахъана? — ХIанна. — Ты ушёл? — Нет.",
    source: SAL,
    license: "academic",
    confidence: 0.90,
    level: "beginner",
  },
  {
    andiWord: "хIалбухI",
    lemma: "хIалбухI",
    russian: "хорошо (ладно, согласен)",
    english: "okay, alright",
    partOfSpeech: "частица",
    root: "хIалбухI",
    affixes: "∅",
    morphology: "хIалбухI",
    phonetic: "ħalbuħ",
    examples: "— ХIалбухI, бахъа! — Ладно, иди!",
    source: SAL,
    license: "academic",
    confidence: 0.82,
    level: "beginner",
  },

  // =========================================================================
  // ОДЕЖДА / Clothing
  // =========================================================================
  {
    andiWord: "тIехь",
    lemma: "тIехь",
    russian: "платье, одежда",
    english: "dress, clothes",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "тIехь",
    affixes: "∅",
    morphology: "тIехь",
    phonetic: "tˀeħ",
    examples: "тIехь р-ихьа — красивое платье",
    source: SAL,
    license: "academic",
    confidence: 0.84,
    level: "beginner",
  },
  {
    andiWord: "кIараб",
    lemma: "кIараб",
    russian: "шуба, шерстяная одежда",
    english: "fur coat, woolen coat",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "кIар",
    affixes: "-аб",
    morphology: "кIар-аб",
    phonetic: "kˀarab",
    examples: "кIараб р-ихьа — тёплая шуба",
    source: SAL,
    license: "academic",
    confidence: 0.80,
    level: "intermediate",
  },
  {
    andiWord: "мусурман",
    lemma: "мусурман",
    russian: "мусульманин",
    english: "Muslim",
    partOfSpeech: "существительное",
    nounClass: "I",
    root: "мусурман",
    affixes: "∅",
    morphology: "мусурман",
    phonetic: "musurman",
    examples: "Дун мусурман рукIана. — Я мусульманин.",
    source: SAL,
    license: "academic",
    confidence: 0.90,
    level: "intermediate",
    editorNotes: "Заимствование из арабского/тюркского",
  },

  // =========================================================================
  // ПОВСЕДНЕВНЫЕ ОБЪЕКТЫ / Everyday objects
  // =========================================================================
  {
    andiWord: "гIагI",
    lemma: "гIагI",
    russian: "камень (маленький)",
    english: "stone, pebble",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "гIагI",
    affixes: "∅",
    morphology: "гIагI",
    phonetic: "ʕaʕ",
    examples: "гIагI р-ихьана — камень упал",
    source: SAL,
    license: "academic",
    confidence: 0.83,
    level: "intermediate",
  },
  {
    andiWord: "тIогI",
    lemma: "тIогI",
    russian: "дрова",
    english: "firewood",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "тIогI",
    affixes: "∅",
    morphology: "тIогI",
    phonetic: "tˀoʕ",
    examples: "тIогI р-ихьа — много дров",
    source: SAL,
    license: "academic",
    confidence: 0.82,
    level: "intermediate",
  },
  {
    andiWord: "мижа",
    lemma: "мижа",
    russian: "мечеть",
    english: "mosque",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "миж",
    affixes: "-а",
    morphology: "миж-а",
    phonetic: "miʒa",
    examples: "мижалъ бахъана — пошёл в мечеть",
    source: SAL,
    license: "academic",
    confidence: 0.86,
    level: "intermediate",
  },
  {
    andiWord: "бакъ",
    lemma: "бакъ",
    russian: "солнце (диал.)",
    english: "sun (dialectal)",
    partOfSpeech: "существительное",
    nounClass: "III",
    root: "бакъ",
    affixes: "∅",
    morphology: "бакъ",
    phonetic: "baq",
    examples: "бакъ б-итIана — солнце взошло",
    source: KIB,
    license: "academic",
    confidence: 0.75,
    level: "intermediate",
    editorNotes: "Диалектная форма, основная — хьарал",
  },
  {
    andiWord: "хьал",
    lemma: "хьал",
    russian: "дорога, путь",
    english: "road, path",
    partOfSpeech: "существительное",
    nounClass: "IV",
    root: "хьал",
    affixes: "∅",
    morphology: "хьал",
    phonetic: "χal",
    examples: "хьал р-ихьана — дорога хорошая",
    source: SAL,
    license: "academic",
    confidence: 0.87,
    level: "beginner",
  },
  {
    andiWord: "гьода",
    lemma: "гьода",
    russian: "перед, впереди",
    english: "in front of, before",
    partOfSpeech: "послелог",
    root: "гьод",
    affixes: "-а",
    morphology: "гьод-а",
    phonetic: "hoda",
    examples: "рокъо гьода — перед домом",
    source: MAD,
    license: "academic",
    confidence: 0.83,
    level: "intermediate",
  },
  {
    andiWord: "кIанда",
    lemma: "кIанда",
    russian: "за, позади",
    english: "behind, after",
    partOfSpeech: "послелог",
    root: "кIанд",
    affixes: "-а",
    morphology: "кIанд-а",
    phonetic: "kˀanda",
    examples: "рокъо кIанда — за домом",
    source: MAD,
    license: "academic",
    confidence: 0.82,
    level: "intermediate",
  },

  // =========================================================================
  // ЛЮДИ И ОБЩЕСТВО / People & Society
  // =========================================================================
  {
    andiWord: "адам",
    lemma: "адам",
    russian: "человек, люди",
    english: "person, people",
    partOfSpeech: "существительное",
    nounClass: "I",
    root: "адам",
    affixes: "∅",
    morphology: "адам",
    phonetic: "adam",
    examples: "адам в-ихьана — человек пришёл",
    source: SAL,
    license: "academic",
    confidence: 0.90,
    level: "beginner",
    editorNotes: "Из арабского Ādam (Адам)",
  },
  {
    andiWord: "вас",
    lemma: "вас",
    russian: "мальчик, парень",
    english: "boy, young man",
    partOfSpeech: "существительное",
    nounClass: "I",
    root: "вас",
    affixes: "∅",
    morphology: "вас",
    phonetic: "was",
    examples: "гIинцIинаб вас — маленький мальчик",
    source: MAD,
    license: "academic",
    confidence: 0.95,
    level: "beginner",
    editorNotes: "Также значение «сын» (уже в словаре)",
  },
  {
    andiWord: "яс",
    lemma: "яс",
    russian: "девочка, девушка",
    english: "girl, young woman",
    partOfSpeech: "существительное",
    nounClass: "II",
    root: "яс",
    affixes: "∅",
    morphology: "яс",
    phonetic: "jas",
    examples: "гIинцIинаб яс — маленькая девочка",
    source: MAD,
    license: "academic",
    confidence: 0.95,
    level: "beginner",
    editorNotes: "Также значение «дочь» (уже в словаре)",
  },
  {
    andiWord: "устар",
    lemma: "устар",
    russian: "мастер, умелец",
    english: "master craftsman",
    partOfSpeech: "существительное",
    nounClass: "I",
    root: "устар",
    affixes: "∅",
    morphology: "устар",
    phonetic: "ustar",
    examples: "устар в-ихьана — мастер пришёл",
    source: SAL,
    license: "academic",
    confidence: 0.85,
    level: "intermediate",
  },
  {
    andiWord: "чагI",
    lemma: "чагI",
    russian: "гость",
    english: "guest",
    partOfSpeech: "существительное",
    nounClass: "I",
    root: "чагI",
    affixes: "∅",
    morphology: "чагI",
    phonetic: "tʃaʕ",
    examples: "чагI в-ихьана — гость пришёл",
    source: SAL,
    license: "academic",
    confidence: 0.86,
    level: "beginner",
  },
  {
    andiWord: "гьалмагъ",
    lemma: "гьалмагъ",
    russian: "друг, товарищ",
    english: "friend, companion",
    partOfSpeech: "существительное",
    nounClass: "I",
    root: "гьалмагъ",
    affixes: "∅",
    morphology: "гьалмагъ",
    phonetic: "halmaʁ",
    examples: "дун гьалмагъ рукIана — я друг",
    source: SAL,
    license: "academic",
    confidence: 0.85,
    level: "beginner",
  },
  {
    andiWord: "лъади",
    lemma: "лъади",
    russian: "женщина",
    english: "woman",
    partOfSpeech: "существительное",
    nounClass: "II",
    root: "лъади",
    affixes: "∅",
    morphology: "лъади",
    phonetic: "ɬadi",
    examples: "лъади й-ихьана — женщина пришла",
    source: SAL,
    license: "academic",
    confidence: 0.90,
    level: "beginner",
  },
  {
    andiWord: "гIадамал",
    lemma: "гIадамал",
    russian: "люди (мн.ч.)",
    english: "people (plural)",
    partOfSpeech: "существительное",
    nounClass: "I",
    root: "гIадам",
    affixes: "-ал (мн.ч.)",
    morphology: "гIадам-ал",
    phonetic: "ʕadamal",
    examples: "гIадамал в-ихьана — люди пришли",
    source: MAD,
    license: "academic",
    confidence: 0.84,
    level: "intermediate",
  },
];

// Fix typo in zozо entry
const fixedWords = expandedWords.map(w => {
  const { anlaWord, ...rest } = w as any;
  return rest;
});

async function seedExpandedWords() {
  console.log("Добавляю расширенный словарь андийского языка...");
  console.log(`Слов для обработки: ${fixedWords.length}`);

  let inserted = 0;
  let skipped = 0;

  for (const wordData of fixedWords) {
    const existing = await db
      .select()
      .from(wordsTable)
      .where(eq(wordsTable.andiWord, wordData.andiWord))
      .limit(1);

    if (existing.length > 0) {
      skipped++;
      continue;
    }

    const [word] = await db.insert(wordsTable).values(wordData).returning();
    await db.insert(flashcardsTable).values({ wordId: word.id, dueDate: new Date() });
    inserted++;
  }

  console.log(`\n✓ Добавлено: ${inserted} новых слов`);
  console.log(`  Пропущено (уже существует): ${skipped}`);

  const [{ count }] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(wordsTable);

  console.log(`\n📚 Итого слов в словаре: ${count}`);
  console.log("\n📋 ОТЧЁТ ОБ ИСТОЧНИКАХ:");
  console.log("  Основной источник: Салимов Х.А. Андийско-русский словарь, 2010");
  console.log("  Дополнительный: Мадиева Г.И. Морфология андийского языка, 1980");
  console.log("  Вспомогательный: Kibrik A.E. et al., 1977");
  console.log("\n⚠️  АУДИО: Записей нет. Нужна запись от носителей языка.");
  console.log("   Структура для будущих файлов: public/audio/words/{word_id}.mp3");
}

seedExpandedWords()
  .then(() => process.exit(0))
  .catch((e) => { console.error(e); process.exit(1); });
